### ISSUE TITLE
UE 4.26.2 Compiled--RML_PlayerController Error: unknown function Toggle Menu 

### ISSUE THREAD

**Issue by JohnwinJia** [Chrizey91/RuntimeMeshLoader#2] opened 2021-10-20 03:35 UTC
![Snipaste_2021-10-20_11-31-12](https://user-images.githubusercontent.com/88176210/138024103-207f0c75-00b7-4fa9-a050-f6c01c39e3de.png)

![Snipaste_2021-10-20_11-30-50](https://user-images.githubusercontent.com/88176210/138024109-bc18720d-3504-42d2-af18-eb5099d4280b.png)

**Comment by maytom2016** [comment] 2021-11-23 10:40
it happen in ue4.25.4 too

**Comment by Chrizey91** [comment] 2021-11-24 18:43
Hi both, I am unable to reproduce this error, even with the same Unreal Engine version (v. 4.25.4).
To me, however, this looks like a simple fix as there seem to be just the references missing.

In your top image (Level Blueprint) select `RMLUserWidget` as the `Class`.
In your lower image (RML_PlayerController) select `RMLUserWidget` as the `Class` again.

Afterwards this should be fixed. Let me know if this works.
If not, please provide clear steps to reproduce the error.

Greetings

**Comment by maytom2016** [comment] 2021-11-25 12:53
1、Your solution about frist problem.It works.
![image](https://user-images.githubusercontent.com/21106644/143444638-376e0a9b-4fd6-4ace-b638-a6ea36a31625.png)
2、The second problem.it doen't works.
![image](https://user-images.githubusercontent.com/21106644/143445197-51ae0e68-3c75-4526-909c-b60fe1f49ff5.png)

**Comment by Chrizey91** [comment] 2021-11-25 12:55
Hi @maytom2016,
you inserted `RML List Entry`, however, it should be `RML User Widget`.
Let me know if that fixes it.

Greetings

**Comment by maytom2016** [comment] 2021-11-25 12:57
I can't find it
![image](https://user-images.githubusercontent.com/21106644/143445728-8cf4879b-1826-4544-94c7-3847e4eff7cf.png)

**Comment by Chrizey91** [comment] 2021-11-25 13:01
Ok, this at least explains the problem: You are missing a class.

I will dig into it later today when I am at home and let you know if I find a solution.

The class should be located at "RuntimeMeshLoader/Content/Example/UI/".

**Comment by maytom2016** [comment] 2021-11-25 13:08
@Chrizey91 thank you for your works.This project has been very really helpful to me.If not, I could still be googling forever.

**Comment by Chrizey91** [comment] 2021-11-26 20:15
Hey @maytom2016,
sorry for not coming back to you yesterday. I wasn't able to reproduce the bug then.

However, I think, today I was finally able to reproduce it and pushed an update that should (hopefully) fix it.
You can either download the whole plugin again, or simply replacte the old `RML_UserWidget.uasset` file with the new one. You will find the file at `[GameRootFolder]/Plugins/RuntimeMeshLoader/Content/Example/UI`

Let me know if this fixes it for you!

> thank you for your works.This project has been very really helpful to me.If not, I could still be googling forever

I cannot express how happy this makes me to know other people love and use the stuff that I created! :)

Greetings

**Comment by maytom2016** [comment] 2021-11-28 07:43
Well,After I download the whole plugin again.and rebuild all project.Then put the file folder
`\RuntimeMeshLoader\Resources\gun` into `C:\Users\PCusername\Documents\RuntimeMeshLoader\Resources` as fbx resources.
run RML_ExampleMap in viewport.it works very well.I guess The problem have been solved.@Chrizey91 Thank you again for your selfless dedication.
![image](https://user-images.githubusercontent.com/21106644/143733933-c1cf16fe-a17f-4c7f-845d-3d8fe7dafa74.png)

**Closed** 2021-11-28 10:49 UTC
